import ExchangesTable from "components/tables/ExchangesTable";
import { NextPage } from "next";
import Head from "next/head";
import React from "react";

const ExchangesPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Cryptocurrency Exchanges</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ExchangesTable />
    </>
  );
};

export default ExchangesPage;
